require('plugins')
require('options')
require('lualine-config')
require('autopairs-config')
require('keybindings')
require('telescope-config')
require('colorizer-config')
require('lsp')
require('trouble-config')
require('dashboard-config')
require('gitsigns-config')
require('toggleterm-config')
require('py-lsp-config')
require('gomove-config')
require('toggle-lsp-diagnostics')
require('indent-blankline-config')
require('nvim-tree-config')
require('tabline-config')
require('treesitter-config')

vim.cmd("colorscheme kanagawa")
vim.cmd[[hi Normal guibg=NONE ctermbg=NONE]]
